export const START_TEST_CONFIG = 'START_TEST_CONFIG';
export const START_TEST_ID_TIMER = 'START_TEST_ID_TIMER';
export const DISPATCH_TEST_RESULT = 'DISPATCH_TEST_RESULT';
export const DISPATCH_RESET_RESULT = 'DISPATCH_RESET_RESULT';
export const CHOICE_TEST = 'CHOICE_TEST';
export const REMOVE_TEST = 'REMOVE_TEST';
